# Copyright 2021-2025 Chris Croome
#
# This file is part of the Webarchitects cv, the CiviCRM command line interface Ansible role.
#
# The Webarchitects cv, the CiviCRM command line interface Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects cv, the CiviCRM command line interface Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects cv, the CiviCRM command line interface Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DEFAULT_VERBOSITY: "1"
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_ERROR_ON_UNDEFINED_VARS: "1"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_INJECT_FACT_VARS: "0"
  ANSIBLE_NOCOWS: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_ROLES_PATH: "${CI_PROJECT_DIR}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  DEBIAN_FRONTEND: "noninteractive"
  DEFAULT_MANAGED_STR: "Ansible managed"
  # GIT_STRATEGY: none
  MOLECULE_VERBOSITY: "0"
  PRE_COMMIT_COLOR: always
  PY_COLORS: "1"
before_script:
  - cd
  - source ~/.profile
  # - mkdir -p builds/${CI_PROJECT_ROOT_NAMESPACE}
  # - cd builds/${CI_PROJECT_ROOT_NAMESPACE}
  # - git clone ${CI_PROJECT_URL}.git
  # - cd ${CI_PROJECT_NAME}
  - cat /etc/debian_version
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
stages:
  - bookworm
  - jammy
  - trixie
  - noble
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20250113
  stage: bookworm
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20250113
  stage: jammy
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20250113
  stage: trixie
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
noble:
  image: registry.git.coop/webarch/containers/images/noble:20250113
  stage: noble
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
...
